spring:
  main:
    banner-mode: 'off'
  aop:
    proxy-target-class: false
---
logging:
  charset:
    console: ${native.encoding:${file.encoding}}
  level:
    root: 'WARN'
    jp.gr.java_conf.stardiopside.sound: 'INFO'
